version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
    commit-message:
      prefix: "deps"
      include: "scope"