name: Build Project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Gradle Permissions
        run: chmod +x ./gradlew

      - name: Build FatJar
        run: ./gradlew fatJar

      - name: Add Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "MCEndgame-${{ github.ref_name }}"
          path: build/libs/*.jar