name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Gradle Permissions
        run: chmod +x ./gradlew

      - name: Build FatJar
        run: ./gradlew fatJar

      - name: Add Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "MCEndgame-${{ github.ref_name }}"
          path: build/libs/*.jar

  publish:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: discord-publish
    steps:
      - name: Call Discord Webhook
        run: |
          BUILD_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$BUILD_URL\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}