name: Discord-Notify

on:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: discord-publish
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: "MCEndgame-${{ github.ref_name }}"
          path: ./artifact

      - name: Unzip Artifact
        run: |
          sudo apt-get install unzip
          unzip ./artifact/* -d ./artifact

      - name: Find JAR File
        run: |
          JAR_FILE=$(find ./artifact -name "*.jar" | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Call Discord Webhook
        run: |
          curl -F "payload_json={\"content\":\"\"}" \
               -F "file=@${{ env.JAR_FILE }}" 
               ${{ secrets.DISCORD_WEBHOOK_URL }}